language: cpp
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install rapidjson-dev
dist: trusty
script: mkdir deps && cd deps && git clone https://github.com/oktal/pistache.git && cd pistache   && mkdir build && cd build && cmake .. && make install && cd ../../../ && mkdir build && cd build && cmake .. && make
compiler:
    - clang
    - gcc
branches:
    only:
        - master

